### ISSUE TITLE
Wrong filenames

### ISSUE THREAD

**Issue by szymon-polaczy** [osomstudio/juniper#11]
After using this command `wp add block --name="Testing big block"` a new block is created with this slug "testing_big_block" but the site tries to load "testing-big-block" which leads to the error below and no block being shown

[11-Sep-2023 07:32:45 UTC] [ Timber ] Error loading your template files: views/blocks/testing-big-block.twig. Make sure one of these files exists.

**Comment by bartnovak** [comment]
Fixed with https://github.com/osomstudio/juniper/releases/tag/1.05.1 .
